name: "Configure helmfile Action For GitHub Actions"
description: "Configure helmfile and many helm plugins in GitHub Actions"

env:
  HELM_VERSION: "3.13.0"
  HELMFILE_VERSION: "0.149.0"
  HELM_DIFF_VERSION: "3.6.0"
  HELM_SECRETS_VERSION: "4.2.1"
  HELM_S3_VERSION: "0.10.0"
  HELM_GIT_VERSION: "0.10.0"
  HELM_X_VERSION: "0.8.1"
  SOPS_VERSION: "v3.8.0"

jobs:
  setup-helm:
    name: Setup Helm
    runs-on: ubuntu-latest
    steps:
      - name: Set up Environment
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz -O /tmp/helm.tar.gz \
              && tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1 \
              && mv /tmp/helm $GITHUB_WORKSPACE/bin/helm \
              && chmod +x $GITHUB_WORKSPACE/bin/helm
        shell: bash

      - name: Install Helmfile
        run: |
          wget https://github.com/helmfile/helmfile/releases/download/v$HELMFILE_VERSION/helmfile_$HELMFILE_VERSION_linux_amd64.tar.gz -O /tmp/helmfile.tar.gz \
          && tar xzf /tmp/helmfile.tar.gz -C /tmp \
          && mv /tmp/helmfile $GITHUB_WORKSPACE/bin/helmfile \
          && chmod +x $GITHUB_WORKSPACE/bin/helmfile
        shell: bash

      - name: Install Helm-diff Plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff --version $HELM_DIFF_VERSION
        shell: bash

      - name: Install Helm-secrets Plugin
        run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version $HELM_SECRETS_VERSION
        shell: bash

      - name: Install Helm-s3 Plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git --version $HELM_S3_VERSION
        shell: bash

      - name: Install Helm-git Plugin
        run: |
          helm plugin install https://github.com/aslafy-z/helm-git --version $HELM_GIT_VERSION
        shell: bash

      - name: Install Helm-x Plugin
        run: |
           helm plugin install https://github.com/mumoshu/helm-x --version $HELM_X_VERSION
        shell: bash

  install-sops:
    name: Install Sops
    runs-on: ubuntu-latest
    steps:
      - name: Install Sops
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: $SOPS_VERSION
