name: "Configure helmfile Action For GitHub Actions"
description: "Configure helmfile and many helm plugins in GitHub Actions"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  helm-version:
    description: "helm version"
    default: "3.13.3"
    required: false
  helmfile-version:
    description: "helmfile version"
    default: "0.149.0"
    required: false
  helm-diff-version:
    description: "helm-diff plugin version"
    default: "3.6.0"
    required: false
  helm-secrets-version:
    description: "helm-secrets plugin version"
    default: "4.2.1"
    required: false
  helm-s3-version:
    description: "helm-s3 plugin version"
    default: "0.10.0"
    required: false
  helm-git-version:
    description: "helm-git plugin version"
    default: "0.10.0"
    required: false
  helm-x-version:
    description: "helm-x plugin version"
    default: "0.8.1"
    required: false
  sops-version:
    description: "sops version"
    default: "3.8.0"
    required: false
  ibmc-version:
    description: "ibmc version"
    default: "2.2.33"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      shell: bash
    # install helm
    - run: |
        wget https://get.helm.sh/helm-v${{ inputs.helm-version }}-linux-amd64.tar.gz -O /tmp/helm.tar.gz \
            && tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1 \
            && mv /tmp/helm $GITHUB_WORKSPACE/bin/helm \
            && chmod +x $GITHUB_WORKSPACE/bin/helm
      shell: bash
    # install helmfile
    - run: |
        wget https://github.com/helmfile/helmfile/releases/download/v${{ inputs.helmfile-version }}/helmfile_${{ inputs.helmfile-version }}_linux_amd64.tar.gz -O /tmp/helmfile.tar.gz \
        && tar xzf /tmp/helmfile.tar.gz -C /tmp \
        && mv /tmp/helmfile $GITHUB_WORKSPACE/bin/helmfile \
        && chmod +x $GITHUB_WORKSPACE/bin/helmfile
      shell: bash
    # install helm-diff
    - run: |
        helm plugin install https://github.com/databus23/helm-diff --version ${{ inputs.helm-diff-version }}
      shell: bash
    # install helm-secrets
    - run: |
        helm plugin install https://github.com/jkroepke/helm-secrets --version ${{ inputs.helm-secrets-version }}
      shell: bash
    # install helm-s3
    - run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git --version ${{ inputs.helm-s3-version }}
      shell: bash
    # install helm-git
    - run: |
        helm plugin install https://github.com/aslafy-z/helm-git --version ${{ inputs.helm-git-version }}
      shell: bash
    # install helm-x
    - run: |
        helm plugin install https://github.com/mumoshu/helm-x --version ${{ inputs.helm-x-version }}
      shell: bash
    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1
      with:
        version: ${{ inputs.sops-version }}
    - name: Install Helm IBMC
      run: |
        helm repo add ibm-helm https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm \
        && helm repo update \
        && helm plugin uninstall ibmc \
        && helm fetch --untar ibm-helm/ibm-object-storage-plugin --version ${{ inputs.ibmc-version }} \
        && helm plugin install ./ibm-object-storage-plugin/helm-ibmc \
        && rm -rf ./ibm-object-storage-plugin \
        && helm ibmc --help

