ibm:
  #only regional endpoints are considered for ibm cloud object storage.
  #user can override to crossregion or singlesite endpoints by setting in pvc.yaml
  us-south: s3.us-south.cloud-object-storage.appdomain.cloud
  us-east: s3.us-east.cloud-object-storage.appdomain.cloud
  eu-gb: s3.eu-gb.cloud-object-storage.appdomain.cloud
  eu-de: s3.eu-de.cloud-object-storage.appdomain.cloud
  jp-tok: s3.jp-tok.cloud-object-storage.appdomain.cloud
  jp-osa: s3.jp-osa.cloud-object-storage.appdomain.cloud
  au-syd: s3.au-syd.cloud-object-storage.appdomain.cloud
  eu-fr2: s3.private.eu-fr2.cloud-object-storage.appdomain.cloud
  ca-tor: s3.ca-tor.cloud-object-storage.appdomain.cloud
  br-sao: s3.br-sao.cloud-object-storage.appdomain.cloud

aws:
  #https://docs.aws.amazon.com/general/latest/gr/s3.html
  us-east-2: s3.us-east-2.amazonaws.com
  us-east-1: s3.us-east-1.amazonaws.com
  us-west-1: s3.us-west-1.amazonaws.com
  us-west-2: s3.us-west-2.amazonaws.com
  eu-west-1: s3.eu-west-1.amazonaws.com
  eu-west-2: s3.eu-west-2.amazonaws.com
  eu-west-3: s3.eu-west-3.amazonaws.com
  eu-south-1: s3.eu-south-1.amazonaws.com
  eu-south-2: s3.eu-south-2.amazonaws.com
  af-south-1: s3.af-south-1.amazonaws.com
  ap-east-1: s3.ap-east-1.amazonaws.com
  ap-south-2: s3.ap-south-2.amazonaws.com
  ap-south-1: s3.ap-south-1.amazonaws.com
  ap-northeast-3: s3.ap-northeast-3.amazonaws.com
  ap-northeast-2: s3.ap-northeast-2.amazonaws.com
  ap-northeast-1: s3.ap-northeast-1.amazonaws.com
  ap-southeast-1: s3.ap-southeast-1.amazonaws.com
  ap-southeast-2: s3.ap-southeast-2.amazonaws.com
  ap-southeast-3: s3.ap-southeast-3.amazonaws.com
  ca-central-1: s3.ca-central-1.amazonaws.com
  eu-central-1: s3.eu-central-1.amazonaws.com
  eu-central-2: s3.eu-central-2.amazonaws.com
  cn-north-1: s3.cn-north-1.amazonaws.com.cn
  cn-northwest-1: s3.cn-northwest-1.amazonaws.com.cn
  eu-north-1: s3.eu-north-1.amazonaws.com
  sa-east-1: s3.sa-east-1.amazonaws.com
  me-south-1: s3.me-south-1.amazonaws.com
  me-central-1: s3.me-central-1.amazonaws.com
  us-gov-east-1: s3.us-gov-east-1.amazonaws.com
  us-gov-west-1: s3.us-gov-west-1.amazonaws.com

wasabi:
  #https://wasabi-support.zendesk.com/hc/en-us/articles/360015106031-What-are-the-service-URLs-for-Wasabi-s-different-storage-regions-
  us-east-1: s3.wasabisys.com
  us-east-2: s3.us-east-2.wasabisys.com
  us-central-1: s3.us-central-1.wasabisys.com
  us-west-1: s3.us-west-1.wasabisys.com
  ca-central-1: s3.ca-central-1.wasabisys.com
  eu-central-1: s3.eu-central-1.wasabisys.com
  eu-central-2: s3.eu-central-2.wasabisys.com
  eu-west-1: s3.eu-west-1.wasabisys.com
  eu-west-2: s3.eu-west-2.wasabisys.com
  ap-northeast-1: s3.ap-northeast-1.wasabisys.com
  ap-northeast-2: s3.ap-northeast-2.wasabisys.com
  ap-southeast-1: s3.ap-southeast-1.wasabisys.com
  ap-southeast-2: s3.ap-southeast-2.wasabisys.com
