---
# ServiceAccount for ibmcloud-object-storage-driver
{{- include "ibm-object-storage-plugin.licenseValidate" .  | required "License must be accepted by setting license key to true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibmcloud-object-storage-driver
  namespace: {{template "ibm-object-storage-plugin.namespace" .}}
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{template "ibm-object-storage-plugin.drivername" .}}
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    release: {{.Release.Name}}
---
# Create SCC / PSP
{{- if contains "OPENSHIFT" (.Values.platform | quote | upper)}}
# Create SCC for OpenShift, both form IKS and RHOCP
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: s3fs-cos-driver-scc
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{template "ibm-object-storage-plugin.drivername" .}}
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    release: {{.Release.Name}}
priority: 0
defaultAddCapabilities: []
allowedCapabilities: []
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
allowHostNetwork: true
allowPrivilegedContainer: false
allowPrivilegeEscalation: true
requiredDropCapabilities:
 - KILL
 - MKNOD
 - SETUID
 - SETGID
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{template "ibm-object-storage-plugin.namespace" .}}:ibmcloud-object-storage-driver
groups: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
{{- end}}
