# ServiceAccount for ibmcloud-object-storage-plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibmcloud-object-storage-plugin
  namespace: {{ template "ibm-object-storage-plugin.namespace" . }}
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
#ClusterRole with minimum permissions required for ibmcloud-object-storage-plugin
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-object-storage-plugin
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["cluster-info"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes", "services"]
  verbs: ["get"]
---
#ClusterRole for giving read secrets permission to ibmcloud-object-storage-plugin
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-object-storage-secret-reader
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  #resourceNames: [""]
  verbs: ["get"]
---
#ClusterRoleBinding for binding ClusterRole "ibmcloud-object-storage-plugin"
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-object-storage-plugin
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: ibmcloud-object-storage-plugin
  namespace: {{ template "ibm-object-storage-plugin.namespace" . }}
roleRef:
  kind: ClusterRole
  name: ibmcloud-object-storage-plugin
  apiGroup: rbac.authorization.k8s.io
---
#ClusterRoleBinding for binding ClusterRole "ibmcloud-object-storage-secret-reader"
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-object-storage-secret-reader
  annotations:
    razee.io/source-url: {{ template "ibm-object-storage-plugin.repoSourceUrl" . }}
    razee.io/build-url: {{ template "ibm-object-storage-plugin.buildUrl" . }}
  labels:
    app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: ibmcloud-object-storage-plugin
  namespace: {{ template "ibm-object-storage-plugin.namespace" . }}
roleRef:
  kind: ClusterRole
  name: ibmcloud-object-storage-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
